### ISSUE TITLE
Pull Requests from outside contributors do not get the correct ref

### ISSUE THREAD

**Issue by cellistigs** [cunningham-lab/neurocaas#83]
Pull Requests from forks/outside contributors (not sure which) don't trigger the right pull in `get_pull_request_ref` action. In particular, look at the code here: 

```  
deploy:
    runs-on: ubuntu-latest
    needs: deploy-check
    if: needs.deploy-check.outputs.triggered == 'true'
    steps:
      - name: get pull request ref
        id: get_pull_request_ref
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{owner}/{repo}/pulls/{issue_id}
          owner: cunningham-lab
          repo: neurocaas
          repository: ${{ github.repository }}
          issue_id: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```

Later, we explicitly call `fromJson(steps.get_pull_request_ref.outputs.data).head.ref` as the output of this step, which will just get the ref for master. We need to find a way to reference the ref of the forking repo. 

Play around with the first solution suggested here: 
https://github.com/actions/checkout/issues/455

this might be useful: 
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
